name: Staging deployment

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: danielbrunolabs-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: danielbrunolabs-ttt-app
  #################################################


jobs:
  build:
    runs-on: ubunto-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
